master:
  push:
    - docker:
        image: node
      stages:
        - name: 依赖安装
          script: npm install cssg -g
        - name: 编译
          script: cd dotnet && cssg compile
    - network: idc
      docker:
        image: mcr.microsoft.com/dotnet/core/sdk:2.1
      stages:
        - name: 测试
          script: cd dotnet && dotnet test
    - docker:
        image: node
      stages:
        - name: 编写文档
          script: cssg write