language: node_js
node_js:
  - '8'
  
before_install:
- npm i -g cssg

jobs:
  include:
    - stage: test_dotnet
      language: csharp
      mono: none
      dotnet: 2.2.402
      script:
      - cd dotnet
      - cssg compile
      - dotnet restore
      - dotnet test
      - cssg write
    - stage: test_iOS
      language: objective-c
      cache: cocoapods 
      podfile: Podfile 
      xcode_workspace: COS_iOS_Test.xcworkspace
      xcode_scheme: COS_iOS_Test
      xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
      # before_install:
      # - pod repo update
      before_script:
      - cd iOS
