language: node_js
node_js:
  - '8'
  
before_install:
- npm i -g cssg

jobs:
  include:
    # - language: csharp
    #   mono: none
    #   dotnet: 2.2.402
    #   script:
    #   - cd dotnet
    #   - cssg compile
    #   - dotnet restore
    #   - dotnet test
    #   - cssg write
    - language: objective-c
      cache: cocoapods 
      podfile: Podfile 
      xcode_workspace: COS_iOS_Test.xcworkspace
      xcode_scheme: COS_iOS_Test
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
      # before_install:
      # - pod repo update
      before_script:
      - cd iOS
