# language: node_js
# node_js:
#   - '8'
  
# before_install:
# - nvm install v8.11.3
# - npm i -g cssg

# jobs:
#   include:
    # - language: csharp
    #   mono: none
    #   dotnet: 2.2.402
    #   script:
    #   - cd dotnet
    #   - cssg compile
    #   - dotnet restore
    #   - dotnet test
    #   - cssg write
    # - osx_image: xcode10.2
    #   language: objective-c
    #   cache: cocoapods 
    #   podfile: Podfile 
    #   xcode_workspace: COS_iOS_Test.xcworkspace
    #   xcode_scheme: COS_iOS_Test
    #   xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
    #   # before_install:
    #   # - pod repo update
    #   before_script:
    #   - cd iOS
    #   - cssg compile
    #   - xcrun instruments -s
    #   - xcrun instruments -w "iPhone X (11.3)" -t "/Applications/Xcode-9.4.1.app/Contents/Applications/Instruments.app/Contents/Resources/templates/Blank.tracetemplate"
    #   intall:
    #   - pod install

language: objective-c
cache: cocoapods 
podfile: Podfile 
xcode_workspace: COS_iOS_Test.xcworkspace
xcode_scheme: COS_iOS_Test
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
# before_install:
# - pod repo update
before_script:
- cd iOS
# - cssg compile
# - xcrun instruments -s
- xcrun instruments -w "iPhone X (11.3)" -t "/Applications/Xcode-9.4.1.app/Contents/Applications/Instruments.app/Contents/Resources/templates/Blank.tracetemplate"
intall:
- pod install
