language: node_js
node_js:
  - '8'
  
before_install:
- npm i -g cssg

jobs:
  include:
    - stage: test
      language: csharp
      mono: none
      dotnet: 2.2.402
      script:
      - cd dotnet
      - cssg compile
      - dotnet restore
      - dotnet test
