language: node_js
node_js:
  - '8'
  
before_install:
- nvm install v8.11.3
- npm i -g cssg

jobs:
  include:
    # - language: csharp
    #   mono: none
    #   dotnet: 2.2.402
    #   script:
    #   - cd dotnet
    #   - cssg compile
    #   - dotnet restore
    #   - dotnet test
    #   - cssg write
    - language: objective-c
      cache: cocoapods 
      podfile: Podfile 
      xcode_workspace: COS_iOS_Test.xcworkspace
      xcode_scheme: COS_iOS_Test
      xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
      before_install:
      - gem install cocoapods -v '1.7.2'
      - cd iOS
      # - pod repo update
      install:
      - pod install

